apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rb-trigger-auth-conn
  namespace: default
spec:
  hashiCorpVault:
    address: http://104.42.169.125:8200
    authentication: token
    credential:
      token: myroot 
    secrets:
    - parameter: host
      key: host
      path: /secret/data/test/rabbitmq      
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: java-rabbitmq-consumer
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 120 # Optional. Default: 300 seconds
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: queue001
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: rb-trigger-auth-conn 
