apiVersion: v1
kind: Secret
metadata:
  name: rb-conn-secret
data:
  host: YW1xcDovL2d1ZXN0Omd1ZXN0QDIwLjIyOC4xMjYuMjM5OjU2NzI=
  
---
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: rb-cluster-trigger-auth-conn
spec:
  secretTargetRef:
    - parameter: host
      name: rb-conn-secret
      key: host
  hashiCorpVault:
   address: http://104.42.169.125:8200
   authentication: token
   credential:
     token: myroot 
   secrets:
   - parameter: queryKey
     key: keda-nr-key
     path: /kv-v1/keda/secret    
---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: java-rabbitmq-consumer
  pollingInterval: 5 # Optional. Default: 30 seconds
  cooldownPeriod: 120 # Optional. Default: 300 seconds
  maxReplicaCount: 20 # Optional. Default: 100
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: queue001
        mode: QueueLength
        value: "5"
      authenticationRef:
        name: rb--cluster-trigger-auth-conn   
        kind: ClusterTriggerAuthentication
